### ISSUE TITLE
Error: Failed to match tag: "int" at: ["n"]

### ISSUE THREAD

**Issue by kunallakhwani** [dannycoates/pem-jwk#5]
When I pass a private key in PEM format to pem2jwk, I get the following error:
```
     Error: Failed to match tag: "int" at: ["n"]
      at DecoderBuffer.error (node_modules/asn1.js/lib/asn1/base/reporter.js:53:11)
      at DERNode.decodeTag [as _decodeTag] (node_modules/asn1.js/lib/asn1/decoders/der.js:67:19)
      at DERNode.decode [as _decode] (node_modules/asn1.js/lib/asn1/base/node.js:302:23)
      at decodeChildren (node_modules/asn1.js/lib/asn1/base/node.js:332:15)
      at Array.some (native)
      at DERNode.decode [as _decode] (node_modules/asn1.js/lib/asn1/base/node.js:329:33)
      at DERNode.decode [as _decode] (node_modules/asn1.js/lib/asn1/base/node.js:263:47)
      at RSAPrivateKey.decode (node_modules/asn1.js/lib/asn1/decoders/der.js:25:20)
      at Entity.decode (node_modules/asn1.js/lib/asn1/api.js:39:32)
      at decodeRsaPrivate (node_modules/pem-jwk/index.js:112:27)
      at pem2jwk (node_modules/pem-jwk/index.js:165:10)
      ..
```
I added some debug logs and looks like pem-jwk receives correct key, and processes it correctly before going to asn1.js.
Do you know what could be wrong?

**Comment by dannycoates** [comment]
Is it an RSA key? It only supports RSA keys right now.

**Comment by kunallakhwani** [comment]
@dannycoates thank you for a quick response. Yes, it is an RSA key.

**Comment by dannycoates** [comment]
In this repo is `test/priv.pem` when I run `openssl rsa -in test/priv.pem -text -noout` It prints something like this:

```
Private-Key: (2048 bit)
modulus:
    00:...
publicExponent: 65537 (0x10001)
privateExponent:
    14:...
prime1:
    00:...
prime2:
    00:...
exponent1:
    1e:...
exponent2:
    00:...
coefficient:
    00:...
```

These are the fields this library expects. If you run the same openssl command on your key and get different fields, this library won't work for you at this time. If you do get the same fields, can you tell me how you generated the key so I can try to reproduce it. Please do **not** send me your key.

**Comment by kunallakhwani** [comment]
I get an error when I run that command.
```
unable to load Private Key
34309:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/crypto/asn1/tasn_dec.c:1344:
34309:error:0D06C03A:asn1 encoding routines:ASN1_D2I_EX_PRIMITIVE:nested asn1 error:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/crypto/asn1/tasn_dec.c:848:
34309:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/crypto/asn1/tasn_dec.c:768:Field=n, Type=RSA
34309:error:0D09A00D:asn1 encoding routines:d2i_PrivateKey:ASN1 lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/crypto/asn1/d2i_pr.c:99:
34309:error:0907B00D:PEM routines:PEM_READ_BIO_PRIVATEKEY:ASN1 lib:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/crypto/pem/pem_pkey.c:125:```

**Comment by dannycoates** [comment]
@kunallakhwani thanks. It looks like that file is damaged. Can you try `openssl rsa -in test/priv.pem -check -noout` with your key?

**Comment by kunallakhwani** [comment]
@dannycoates exactly the same error with `-check` too

**Comment by dannycoates** [comment]
If openssl can't read the file I don't think there's anything I can do here, unfortunately.

**Comment by kunallakhwani** [comment]
@dannycoates thanks for your help. If I find something I will let you know.

**Comment by kunallakhwani** [comment]
encoding for incorrect for my key. figured out the problem. Closing this issue. Thanks for your help.
